remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: Blackboard QA Docs
description: Documentation for Blackboard QA processes
url: "https://walter-gaitan.github.io"
baseurl: "/blackboard-qa-docs"